---
- import_tasks: "configure.yml"
- import_tasks: "service.yml"

- name: Force Time Sync
  block:
    - name: Force Time Sync
      command: "chronyc -a 'burst 4/4'"
      register: chrony_result
  rescue:
    - debug:
        msg: "Encountered common Chrony error. Occurs when a time server was not available when chronyd started - bumping."
      when: chrony_result.rc == 1 and "'503 No such source' in chrony_result.stdout"
    - systemd:
        state: restarted
        name: chronyd
        enabled: yes
      when: chrony_result.rc == 1 and "'503 No such source' in chrony_result.stdout"

- name: 'Force time sync'
  command: "chronyc -a makestep"

- import_tasks: "sync.yml"
